// ── 3-Month Seed Data (May – July 2026) ──────────────────────────────────────

export const SEED_STAFF = [
  { id:1,  name:"Pastor James Russell",   role:"Senior Pastor",        dept:"Leadership",  email:"james@church.org",    phone:"555-0101", status:"Active", startDate:"2015-03-01", salary:95000 },
  { id:2,  name:"Maria Thompson",         role:"Executive Pastor",     dept:"Leadership",  email:"maria@church.org",    phone:"555-0102", status:"Active", startDate:"2016-06-15", salary:82000 },
  { id:3,  name:"David Chen",             role:"Worship Director",     dept:"Worship",     email:"david@church.org",    phone:"555-0103", status:"Active", startDate:"2018-01-10", salary:68000 },
  { id:4,  name:"Sarah Williams",         role:"Children's Director",  dept:"Children",    email:"sarah@church.org",    phone:"555-0104", status:"Active", startDate:"2019-04-22", salary:62000 },
  { id:5,  name:"Michael Brown",          role:"Finance Director",     dept:"Finance",     email:"michael@church.org",  phone:"555-0105", status:"Active", startDate:"2017-09-01", salary:75000 },
  { id:6,  name:"Jennifer Davis",         role:"Communications Dir.",  dept:"Marketing",   email:"jennifer@church.org", phone:"555-0106", status:"Active", startDate:"2020-02-14", salary:60000 },
  { id:7,  name:"Robert Garcia",          role:"Youth Pastor",         dept:"Youth",       email:"robert@church.org",   phone:"555-0107", status:"Active", startDate:"2021-07-01", salary:58000 },
  { id:8,  name:"Angela Martinez",        role:"Office Manager",       dept:"Admin",       email:"angela@church.org",   phone:"555-0108", status:"Active", startDate:"2018-11-01", salary:52000 },
  { id:9,  name:"Dr. Karen Osei",         role:"Counseling Pastor",    dept:"Pastoral",    email:"karen@church.org",    phone:"555-0109", status:"Active", startDate:"2022-03-15", salary:64000 },
  { id:10, name:"Marcus Lee",             role:"Tech & Media Dir.",    dept:"Tech",        email:"marcus@church.org",   phone:"555-0110", status:"Active", startDate:"2023-01-09", salary:55000 },
];

export const SEED_MINISTRIES = [
  { id:1, name:"Worship & Arts",      leader:"David Chen",      members:45,  volunteers:12, status:"Active", budget:18000, spent:10800, description:"Music, choir, creative arts" },
  { id:2, name:"Children's Ministry", leader:"Sarah Williams",  members:120, volunteers:28, status:"Active", budget:22000, spent:15400, description:"Nursery through 5th grade" },
  { id:3, name:"Youth Ministry",      leader:"Robert Garcia",   members:85,  volunteers:15, status:"Active", budget:16000, spent:11200, description:"Middle & high school" },
  { id:4, name:"Life Groups",         leader:"Maria Thompson",  members:210, volunteers:18, status:"Active", budget:8000,  spent:4200,  description:"Small group community — 6 active groups" },
  { id:5, name:"Outreach & Missions", leader:"Pastor Russell",  members:60,  volunteers:22, status:"Active", budget:35000, spent:19600, description:"Local & global missions" },
  { id:6, name:"Prayer Ministry",     leader:"Angela Martinez", members:40,  volunteers:8,  status:"Active", budget:3000,  spent:1100,  description:"Intercession & prayer" },
  { id:7, name:"Hospitality",         leader:"Jennifer Davis",  members:55,  volunteers:30, status:"Active", budget:12000, spent:7800,  description:"Welcome & guest services" },
  { id:8, name:"Men's Ministry",      leader:"Michael Brown",   members:75,  volunteers:6,  status:"Active", budget:9000,  spent:5400,  description:"Men's discipleship" },
];

export const SEED_LIFE_GROUPS = [
  {
    id:1, name:"Russell LifeGroup", leader:"Rex & Jeanene Russell", day:"Sunday", time:"6:00 PM",
    location:"Church Campus – Rm 201", status:"Active",
    members:[
  { id: 1, name:"Kathy Aylwin", phone:"555-2001", email:"kathy.aylwin@email.com", joined:"2024-11-03", role:"Member", attendance:67, lastContact:"2026-07-20" },
  { id: 2, name:"Richard Aylwin", phone:"555-2002", email:"richard.aylwin@email.com", joined:"2024-12-08", role:"Member", attendance:77, lastContact:"2026-07-18" },
  { id: 3, name:"Taylor Bankston", phone:"555-2003", email:"taylor.bankston@email.com", joined:"2024-04-14", role:"Member", attendance:68, lastContact:"2026-07-20" },
  { id: 4, name:"John Barnett", phone:"555-2004", email:"john.barnett@email.com", joined:"2024-11-03", role:"Member", attendance:94, lastContact:"2026-07-20" },
  { id: 5, name:"Tracy Carroll", phone:"555-2005", email:"tracy.carroll@email.com", joined:"2024-10-13", role:"Member", attendance:87, lastContact:"2026-07-20" },
  { id: 6, name:"Joshua Clay", phone:"555-2006", email:"joshua.clay@email.com", joined:"2024-01-07", role:"Member", attendance:65, lastContact:"2026-07-18" },
  { id: 7, name:"Kemarrae Clay", phone:"555-2007", email:"kemarrae.clay@email.com", joined:"2024-04-14", role:"Member", attendance:92, lastContact:"2026-07-14" },
  { id: 8, name:"Terry Culbertson", phone:"555-2008", email:"terry.culbertson@email.com", joined:"2024-01-07", role:"Member", attendance:95, lastContact:"2026-07-18" },
  { id: 9, name:"Traci Culbertson", phone:"555-2009", email:"traci.culbertson@email.com", joined:"2024-12-08", role:"Member", attendance:94, lastContact:"2026-07-20" },
  { id:10, name:"Paul Dentremont", phone:"555-2010", email:"paul.dentremont@email.com", joined:"2024-04-14", role:"Member", attendance:88, lastContact:"2026-07-14" },
  { id:11, name:"Lauren Ellington", phone:"555-2011", email:"lauren.ellington@email.com", joined:"2024-05-05", role:"Member", attendance:60, lastContact:"2026-07-19" },
  { id:12, name:"Travis Ellington", phone:"555-2012", email:"travis.ellington@email.com", joined:"2024-12-08", role:"Member", attendance:87, lastContact:"2026-07-13" },
  { id:13, name:"Lauren Funderburk", phone:"555-2013", email:"lauren.funderburk@email.com", joined:"2024-05-05", role:"Member", attendance:69, lastContact:"2026-07-18" },
  { id:14, name:"Becki Gourley", phone:"555-2014", email:"becki.gourley@email.com", joined:"2023-09-10", role:"Member", attendance:81, lastContact:"2026-07-20" },
  { id:15, name:"Chris Gourley", phone:"555-2015", email:"chris.gourley@email.com", joined:"2024-02-11", role:"Member", attendance:84, lastContact:"2026-07-20" },
  { id:16, name:"Ashley Hasty", phone:"555-2016", email:"ashley.hasty@email.com", joined:"2024-06-16", role:"Member", attendance:82, lastContact:"2026-07-14" },
  { id:17, name:"Shane Hasty", phone:"555-2017", email:"shane.hasty@email.com", joined:"2024-05-05", role:"Member", attendance:62, lastContact:"2026-07-16" },
  { id:18, name:"Aysha Hoffman", phone:"555-2018", email:"aysha.hoffman@email.com", joined:"2024-09-01", role:"Member", attendance:67, lastContact:"2026-07-20" },
  { id:19, name:"Todd Hoffman", phone:"555-2019", email:"todd.hoffman@email.com", joined:"2024-02-11", role:"Member", attendance:95, lastContact:"2026-07-17" },
  { id:20, name:"David Hook", phone:"555-2020", email:"david.hook@email.com", joined:"2023-10-15", role:"Member", attendance:100, lastContact:"2026-07-14" },
  { id:21, name:"Michelle Hook", phone:"555-2021", email:"michelle.hook@email.com", joined:"2023-11-05", role:"Member", attendance:83, lastContact:"2026-07-14" },
  { id:22, name:"Bryan Hufferd", phone:"555-2022", email:"bryan.hufferd@email.com", joined:"2024-04-14", role:"Member", attendance:64, lastContact:"2026-07-20" },
  { id:23, name:"Debra Hufferd", phone:"555-2023", email:"debra.hufferd@email.com", joined:"2024-11-03", role:"Member", attendance:74, lastContact:"2026-07-17" },
  { id:24, name:"Ryan Kendrick", phone:"555-2024", email:"ryan.kendrick@email.com", joined:"2024-02-11", role:"Member", attendance:74, lastContact:"2026-07-20" },
  { id:25, name:"Bill Killian", phone:"555-2025", email:"bill.killian@email.com", joined:"2024-07-07", role:"Member", attendance:77, lastContact:"2026-07-16" },
  { id:26, name:"Gary Killian", phone:"555-2026", email:"gary.killian@email.com", joined:"2024-11-03", role:"Member", attendance:83, lastContact:"2026-07-19" },
  { id:27, name:"Ashley Klein", phone:"555-2027", email:"ashley.klein@email.com", joined:"2024-06-16", role:"Member", attendance:82, lastContact:"2026-07-18" },
  { id:28, name:"Robby Klein", phone:"555-2028", email:"robby.klein@email.com", joined:"2024-11-03", role:"Member", attendance:77, lastContact:"2026-07-20" },
  { id:29, name:"Charles Lewis", phone:"555-2029", email:"charles.lewis@email.com", joined:"2024-10-13", role:"Member", attendance:100, lastContact:"2026-07-19" },
  { id:30, name:"Sherry Lewis", phone:"555-2030", email:"sherry.lewis@email.com", joined:"2024-09-01", role:"Member", attendance:75, lastContact:"2026-07-19" },
  { id:31, name:"Jeannie McNutt", phone:"555-2031", email:"jeannie.mcnutt@email.com", joined:"2024-08-18", role:"Member", attendance:84, lastContact:"2026-07-17" },
  { id:32, name:"Rusti Morris", phone:"555-2032", email:"rusti.morris@email.com", joined:"2023-11-05", role:"Member", attendance:100, lastContact:"2026-07-11" },
  { id:33, name:"Rusti Morris Jr", phone:"555-2033", email:"rusti.jr@email.com", joined:"2024-04-14", role:"Member", attendance:80, lastContact:"2026-07-20" },
  { id:34, name:"CJ Newell", phone:"555-2034", email:"cj.newell@email.com", joined:"2024-04-14", role:"Member", attendance:62, lastContact:"2026-07-13" },
  { id:35, name:"Jessica Newell", phone:"555-2035", email:"jessica.newell@email.com", joined:"2024-07-07", role:"Member", attendance:77, lastContact:"2026-07-20" },
  { id:36, name:"Thomas Palmer", phone:"555-2036", email:"thomas.palmer@email.com", joined:"2024-04-14", role:"Member", attendance:96, lastContact:"2026-07-13" },
  { id:37, name:"Tonda Palmer", phone:"555-2037", email:"tonda.palmer@email.com", joined:"2024-04-14", role:"Member", attendance:91, lastContact:"2026-07-20" },
  { id:38, name:"Codee Phelps", phone:"555-2038", email:"codee.phelps@email.com", joined:"2023-11-05", role:"Member", attendance:89, lastContact:"2026-07-19" },
  { id:39, name:"Jonathan Phelps", phone:"555-2039", email:"jonathan.phelps@email.com", joined:"2024-05-05", role:"Member", attendance:68, lastContact:"2026-07-18" },
  { id:40, name:"Chris Pidgeon", phone:"555-2040", email:"chris.pidgeon@email.com", joined:"2024-12-08", role:"Member", attendance:95, lastContact:"2026-07-11" },
  { id:41, name:"Linda Renaud", phone:"555-2041", email:"linda.renaud@email.com", joined:"2024-05-05", role:"Member", attendance:97, lastContact:"2026-07-20" },
  { id:42, name:"Norm Renaud", phone:"555-2042", email:"norm.renaud@email.com", joined:"2023-11-05", role:"Member", attendance:97, lastContact:"2026-07-20" },
  { id:43, name:"Travis Roberson", phone:"555-2043", email:"travis.roberson@email.com", joined:"2024-06-16", role:"Member", attendance:74, lastContact:"2026-07-19" },
  { id:44, name:"Jeanene Russell", phone:"555-2044", email:"jeanene.russell@email.com", joined:"2024-09-01", role:"Leader", attendance:91, lastContact:"2026-07-20" },
  { id:45, name:"Rex Russell", phone:"555-2045", email:"rex.russell@email.com", joined:"2023-09-10", role:"Main Leader", attendance:63, lastContact:"2026-07-20" },
  { id:46, name:"Janet Scarbrough", phone:"555-2046", email:"janet.scarbrough@email.com", joined:"2024-03-03", role:"Member", attendance:100, lastContact:"2026-07-19" },
  { id:47, name:"Mike Scarbrough", phone:"555-2047", email:"mike.scarbrough@email.com", joined:"2023-09-10", role:"Leader", attendance:87, lastContact:"2026-07-14" },
  { id:48, name:"Cody Sears", phone:"555-2048", email:"cody.sears@email.com", joined:"2024-02-11", role:"Member", attendance:84, lastContact:"2026-07-20" },
  { id:49, name:"Angela Shelton", phone:"555-2049", email:"angela.shelton@email.com", joined:"2024-10-13", role:"Member", attendance:89, lastContact:"2026-07-11" },
  { id:50, name:"Emily Shelton", phone:"555-2050", email:"emily.shelton@email.com", joined:"2024-05-05", role:"Member", attendance:95, lastContact:"2026-07-20" },
  { id:51, name:"Wesley Shelton", phone:"555-2051", email:"wesley.shelton@email.com", joined:"2024-11-03", role:"Member", attendance:67, lastContact:"2026-07-11" },
  { id:52, name:"James Stubblefield", phone:"555-2052", email:"james.stubblefield@email.com", joined:"2023-09-10", role:"Member", attendance:77, lastContact:"2026-07-13" },
  { id:53, name:"Lorrie Stubblefield", phone:"555-2053", email:"lorrie.stubblefield@email.com", joined:"2024-02-11", role:"Member", attendance:78, lastContact:"2026-07-20" },
  { id:54, name:"Pam Swaim", phone:"555-2054", email:"pam.swaim@email.com", joined:"2024-03-03", role:"Member", attendance:89, lastContact:"2026-07-20" },
  { id:55, name:"Ashley Thomas", phone:"555-2055", email:"ashley.thomas@email.com", joined:"2024-12-08", role:"Member", attendance:76, lastContact:"2026-07-11" },
  { id:56, name:"Jacob Thomas", phone:"555-2056", email:"jacob.thomas@email.com", joined:"2023-09-10", role:"Member", attendance:71, lastContact:"2026-07-11" },
  { id:57, name:"Austin Whitaker", phone:"555-2057", email:"austin.whitaker@email.com", joined:"2023-11-05", role:"Member", attendance:66, lastContact:"2026-07-17" },
  { id:58, name:"Jessie Whitaker", phone:"555-2058", email:"jessie.whitaker@email.com", joined:"2023-10-15", role:"Member", attendance:100, lastContact:"2026-07-11" },
  { id:59, name:"Ken Whitaker", phone:"555-2059", email:"ken.whitaker@email.com", joined:"2024-10-13", role:"Member", attendance:72, lastContact:"2026-07-19" },
  { id:60, name:"Wendy Whitaker", phone:"555-2060", email:"wendy.whitaker@email.com", joined:"2024-06-16", role:"Member", attendance:70, lastContact:"2026-07-11" },
  { id:61, name:"Michael Williamson", phone:"555-2061", email:"michael.williamson@email.com", joined:"2023-09-10", role:"Member", attendance:93, lastContact:"2026-07-20" },
  { id:62, name:"Sharon Williamson", phone:"555-2062", email:"sharon.williamson@email.com", joined:"2024-10-13", role:"Member", attendance:80, lastContact:"2026-07-16" },
  { id:63, name:"David Young", phone:"555-2063", email:"david.young@email.com", joined:"2024-01-07", role:"Member", attendance:67, lastContact:"2026-07-13" }
    ]
  },
];

export const SEED_PRAYER = [
  // MAY
  { id:101, requester:"Linda Hawkins",       group:"Russell LifeGroup",   request:"Healing from knee replacement surgery — recovering at home",                              category:"Health",   status:"Answered", date:"2026-05-04", followUp:"2026-05-18", followUpNote:"Back on her feet! Attended service for the first time in 3 weeks.", private:false },
  { id:102, requester:"Tom & Amy Reed",      group:"Northside Connect",   request:"Tom received three job interviews after 4 months of searching",                          category:"Career",   status:"Answered", date:"2026-05-07", followUp:"2026-06-01", followUpNote:"Tom accepted a position as Project Manager at Hartwell Industries — praise God!", private:false },
  { id:103, requester:"Marcus Johnson",      group:"Northside Connect",   request:"Struggling with anxiety and loneliness since relocating from Atlanta",                   category:"Mental Health", status:"Active", date:"2026-05-12", followUp:"2026-06-12", followUpNote:"Connected with Dr. Osei for pastoral counseling — seeing progress.",private:false },
  { id:104, requester:"Anonymous",           group:"Downtown Disciples",  request:"Marriage under serious strain — spouse has suggested separation",                        category:"Family",   status:"Active",   date:"2026-05-14", followUp:null,          followUpNote:"", private:true  },
  { id:105, requester:"Joseph Turner",       group:"Seniors Circle",      request:"Wife Mae diagnosed with early-stage diabetes — wisdom for dietary changes",               category:"Health",   status:"Answered", date:"2026-05-18", followUp:"2026-06-05", followUpNote:"Mae meeting weekly with nutritionist — blood sugar numbers improving significantly.", private:false },
  { id:106, requester:"Youth Group",         group:"Young Adults Group",  request:"Safe travel & spiritual fruit on summer mission trip to Guatemala",                       category:"Missions", status:"Answered", date:"2026-05-20", followUp:"2026-07-05", followUpNote:"Team of 14 returned safely — built 2 classrooms and led 3 VBS sessions. Incredible fruit.", private:false },
  { id:107, requester:"Felicia Grant",       group:"Russell LifeGroup",   request:"Custody battle over her daughter — court date June 12",                                  category:"Family",   status:"Answered", date:"2026-05-25", followUp:"2026-06-14", followUpNote:"Court ruled in her favor — full custody granted. Church family celebrated together Sunday.", private:false },
  // JUNE
  { id:108, requester:"Edwin Hawkins",       group:"Russell LifeGroup",   request:"Business struggling — considering closing his restaurant of 9 years",                    category:"Finances", status:"Active",   date:"2026-06-02", followUp:"2026-07-01", followUpNote:"Received a small business grant through the city — staying open through Q3.", private:false },
  { id:109, requester:"Diana Okafor",        group:"Russell LifeGroup",   request:"Mother in Nigeria critically ill — cannot travel due to visa issues",                    category:"Family",   status:"Answered", date:"2026-06-08", followUp:"2026-07-02", followUpNote:"Mother stabilized and discharged. Diana's visa approved — flew out July 3rd.", private:false },
  { id:110, requester:"Uriel Castillo",      group:"Young Adults Group",  request:"First-generation college student — struggling academically, considering dropping out",   category:"Career",   status:"Active",   date:"2026-06-10", followUp:"2026-07-08", followUpNote:"Paired with Isaiah Brooks as mentor — passing all courses this semester.", private:false },
  { id:111, requester:"Elijah James",        group:"Eastside Families",   request:"Prodigal son situation — oldest son walked away from faith 2 years ago",                 category:"Family",   status:"Active",   date:"2026-06-15", followUp:null,          followUpNote:"", private:false },
  { id:112, requester:"Katherine Bell",      group:"Seniors Circle",      request:"Praise — 50th wedding anniversary! Thanksgiving to God for faithfulness",                category:"Praise",   status:"Answered", date:"2026-06-18", followUp:"2026-06-21", followUpNote:"Church family surprised them at Sunday service with a reception. Beautiful moment.", private:false },
  { id:113, requester:"Priya Sharma",        group:"Northside Connect",   request:"Navigating faith conversation with unbelieving husband — wisdom and grace needed",       category:"Family",   status:"Active",   date:"2026-06-20", followUp:"2026-07-15", followUpNote:"Husband attended service for the first time on June 29 — heart is softening.", private:false },
  { id:114, requester:"Children's Ministry", group:"",                    request:"Three kids in our program currently in foster care — protection, stability, and love",    category:"Children", status:"Active",   date:"2026-06-22", followUp:null,          followUpNote:"", private:false },
  { id:115, requester:"Ronald Shaw",         group:"Downtown Disciples",  request:"Recovering from alcohol dependency — 60 days sober, needs accountability",              category:"Recovery", status:"Active",   date:"2026-06-25", followUp:"2026-07-20", followUpNote:"90 days sober as of July 25. Accountability partner assigned from Men's Ministry.", private:false },
  // JULY
  { id:116, requester:"Brianna Scott",       group:"Eastside Families",   request:"Accepted to nursing program — provision for tuition and confidence for the challenge",   category:"Career",   status:"Active",   date:"2026-07-01", followUp:null,          followUpNote:"", private:false },
  { id:117, requester:"Hannah Kim",          group:"Russell LifeGroup",   request:"Grandmother's final days — family peace and a good passing",                            category:"Health",   status:"Answered", date:"2026-07-06", followUp:"2026-07-14", followUpNote:"Grandmother passed peacefully July 12. Family gathered; Pastor Russell officiated the service.", private:false },
  { id:118, requester:"Olivia Mensah",       group:"Downtown Disciples",  request:"Work environment is hostile — being passed over for promotion due to faith",             category:"Career",   status:"Active",   date:"2026-07-08", followUp:null,          followUpNote:"", private:false },
  { id:119, requester:"Mildred Okafor",      group:"Seniors Circle",      request:"Praise — cancer screening came back clear after 2 years of monitoring!",                category:"Praise",   status:"Answered", date:"2026-07-10", followUp:"2026-07-13", followUpNote:"Shared her testimony in service July 13 — brought many to tears. Powerful moment.", private:false },
  { id:120, requester:"Nathan Fox",          group:"Downtown Disciples",  request:"Wife Claire 12 weeks pregnant after two miscarriages — peace and a healthy pregnancy",  category:"Health",   status:"Active",   date:"2026-07-14", followUp:null,          followUpNote:"", private:false },
  { id:121, requester:"Yusuf Afolabi",       group:"Young Adults Group",  request:"Pursuing calling to ministry — wisdom about seminary and next steps",                   category:"Calling",  status:"Active",   date:"2026-07-17", followUp:null,          followUpNote:"", private:false },
  { id:122, requester:"Anonymous",           group:"Russell LifeGroup",   request:"Dealing with grief after pregnancy loss — needs pastoral support",                      category:"Grief",    status:"Active",   date:"2026-07-20", followUp:null,          followUpNote:"", private:true  },
  { id:123, requester:"Grace Kim",           group:"Northside Connect",   request:"Praise — baby born healthy after high-risk pregnancy! Mother and baby doing great!",     category:"Praise",   status:"Answered", date:"2026-07-22", followUp:"2026-07-22", followUpNote:"Baby Eliana born July 21st, 7 lbs 4 oz. Church family blessed them Sunday.", private:false },
];

// ── Events — 3-month calendar ─────────────────────────────────────────────────
export const SEED_EVENTS = [
  // MAY 2026
  { id:201, title:"Sunday Worship Service",         date:"2026-05-03", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:342, notes:"Mother's Day card giveaway prep" },
  { id:202, title:"Life Group Leaders Huddle",      date:"2026-05-05", time:"6:30 PM",  location:"Conf. Room A",        type:"Meeting",  lead:"Maria Thompson",  attendees:8,   notes:"Summer planning + care check-ins" },
  { id:203, title:"Men's Ministry Breakfast",       date:"2026-05-10", time:"8:00 AM",  location:"Fellowship Hall",     type:"Ministry", lead:"Michael Brown",   attendees:62,  notes:"Speaker: Dr. Kevin Amos on fatherhood" },
  { id:204, title:"Mother's Day Sunday Service",    date:"2026-05-10", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:521, notes:"Special recognition for mothers — overflow seating used" },
  { id:205, title:"VBS Planning Meeting",           date:"2026-05-12", time:"6:00 PM",  location:"Room 104",            type:"Meeting",  lead:"Sarah Williams",  attendees:14,  notes:"Theme reveal: Jungle Journey. Volunteer sign-ups open" },
  { id:206, title:"Sunday Worship Service",         date:"2026-05-17", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:368, notes:"" },
  { id:207, title:"Women's Bible Study",            date:"2026-05-19", time:"9:30 AM",  location:"Room 104",            type:"Study",    lead:"Maria Thompson",  attendees:41,  notes:"Book of Esther — Week 4 of 6" },
  { id:208, title:"Youth Lock-In",                  date:"2026-05-23", time:"9:00 PM",  location:"Youth Wing",          type:"Youth",    lead:"Robert Garcia",   attendees:47,  notes:"End-of-school celebration. Parents pickup 7am" },
  { id:209, title:"Sunday Worship Service",         date:"2026-05-24", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:355, notes:"Memorial Day weekend — expected lower attendance" },
  { id:210, title:"Finance Committee Meeting",      date:"2026-05-27", time:"6:00 PM",  location:"Conf. Room B",        type:"Meeting",  lead:"Michael Brown",   attendees:6,   notes:"FY review + summer budget projections" },
  { id:211, title:"Sunday Worship Service",         date:"2026-05-31", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:361, notes:"Guest musician: Elevation Worship team member" },
  // JUNE 2026
  { id:212, title:"VBS — Jungle Journey (Day 1)",   date:"2026-06-08", time:"9:00 AM",  location:"Children's Wing",     type:"VBS",      lead:"Sarah Williams",  attendees:138, notes:"Record registration — 138 kids enrolled" },
  { id:213, title:"VBS — Jungle Journey (Day 2)",   date:"2026-06-09", time:"9:00 AM",  location:"Children's Wing",     type:"VBS",      lead:"Sarah Williams",  attendees:141, notes:"" },
  { id:214, title:"VBS — Jungle Journey (Day 3)",   date:"2026-06-10", time:"9:00 AM",  location:"Children's Wing",     type:"VBS",      lead:"Sarah Williams",  attendees:136, notes:"" },
  { id:215, title:"VBS — Jungle Journey (Day 4)",   date:"2026-06-11", time:"9:00 AM",  location:"Children's Wing",     type:"VBS",      lead:"Sarah Williams",  attendees:143, notes:"Family Night — parents invited" },
  { id:216, title:"VBS — Jungle Journey (Day 5)",   date:"2026-06-12", time:"9:00 AM",  location:"Children's Wing",     type:"VBS",      lead:"Sarah Williams",  attendees:152, notes:"Closing ceremony + 6 kids made decisions for Christ" },
  { id:217, title:"Sunday Worship Service",         date:"2026-06-07", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:374, notes:"VBS Sunday kickoff message" },
  { id:218, title:"Sunday Worship Service",         date:"2026-06-14", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:389, notes:"VBS celebration — 3 families joined church" },
  { id:219, title:"Mission Trip Send-Off Service",  date:"2026-06-21", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:395, notes:"Commissioning 14 youth & adults for Guatemala" },
  { id:220, title:"Guatemala Mission Trip",         date:"2026-06-22", time:"6:00 AM",  location:"International",       type:"Missions", lead:"Robert Garcia",   attendees:14,  notes:"7-day trip. Built 2 classrooms, 3 VBS sessions, 20+ salvations" },
  { id:221, title:"Leadership Development Seminar", date:"2026-06-17", time:"9:00 AM",  location:"Fellowship Hall",     type:"Training", lead:"Maria Thompson",  attendees:22,  notes:"Life Group leaders + ministry heads. Guest trainer Dr. Hill" },
  { id:222, title:"Summer Kickoff BBQ",             date:"2026-06-28", time:"1:00 PM",  location:"Church Grounds",      type:"Social",   lead:"Hospitality Team",attendees:287, notes:"Free community event — 41 visitors, 6 first-time contacts" },
  { id:223, title:"Sunday Worship Service",         date:"2026-06-28", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:401, notes:"Mission team returns Sunday — testimonies shared" },
  // JULY 2026
  { id:224, title:"Sunday Worship Service",         date:"2026-07-05", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:356, notes:"Independence Day weekend" },
  { id:225, title:"Mission Team Debrief & Worship", date:"2026-07-06", time:"6:00 PM",  location:"Main Sanctuary",     type:"Worship",  lead:"Robert Garcia",   attendees:198, notes:"Mission team shared testimonies — powerful night of worship" },
  { id:226, title:"Life Group Check-In Roundtable", date:"2026-07-07", time:"6:30 PM",  location:"Conf. Room A",        type:"Meeting",  lead:"Maria Thompson",  attendees:9,   notes:"Summer attendance review + fall sign-up planning" },
  { id:227, title:"Summer Revival Night 1",         date:"2026-07-11", time:"7:00 PM",  location:"Main Sanctuary",     type:"Revival",  lead:"Guest: Bish. Cole",attendees:412, notes:"Guest speaker Bishop Raymond Cole. Standing room only." },
  { id:228, title:"Sunday Worship Service",         date:"2026-07-12", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:388, notes:"" },
  { id:229, title:"Back-to-School Drive Launch",    date:"2026-07-13", time:"9:00 AM",  location:"Lobby",               type:"Outreach", lead:"Outreach Team",   attendees:0,   notes:"Drop boxes placed in lobby and 3 partner locations" },
  { id:230, title:"Women's Conference — Day 1",     date:"2026-07-18", time:"9:00 AM",  location:"Main Sanctuary",     type:"Conference",lead:"Maria Thompson",  attendees:184, notes:"Theme: Walking in Purpose. Speaker: Pastor Diane Carter" },
  { id:231, title:"Women's Conference — Day 2",     date:"2026-07-19", time:"9:00 AM",  location:"Main Sanctuary",     type:"Conference",lead:"Maria Thompson",  attendees:201, notes:"Sold out. Overflow room opened. Powerful altar call." },
  { id:232, title:"Summer Revival Night 2",         date:"2026-07-18", time:"7:00 PM",  location:"Main Sanctuary",     type:"Revival",  lead:"Guest: Bish. Cole",attendees:388, notes:"" },
  { id:233, title:"Sunday Worship Service",         date:"2026-07-19", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:392, notes:"Women's Conference Sunday" },
  { id:234, title:"Summer Revival Night 3",         date:"2026-07-25", time:"7:00 PM",  location:"Main Sanctuary",     type:"Revival",  lead:"Guest: Bish. Cole",attendees:445, notes:"Largest revival crowd of the series — 18 salvations" },
  { id:235, title:"Sunday Worship Service",         date:"2026-07-26", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"Pastor Russell",  attendees:408, notes:"Follow-up Sunday for revival decisions" },
  { id:236, title:"Finance Committee Meeting",      date:"2026-07-28", time:"6:00 PM",  location:"Conf. Room B",        type:"Meeting",  lead:"Michael Brown",   attendees:6,   notes:"Q3 budget review" },
  { id:237, title:"Fall Planning All-Staff Meeting",date:"2026-07-29", time:"9:00 AM",  location:"Fellowship Hall",     type:"Meeting",  lead:"Pastor Russell",  attendees:10,  notes:"Vision for fall semester — new series, Life Group sign-ups" },
  { id:238, title:"Back-to-School Drive Distribution",date:"2026-08-02",time:"9:00 AM", location:"Lobby",              type:"Outreach", lead:"Outreach Team",   attendees:0,   notes:"Volunteer signup open" },
  { id:239, title:"Fall Kickoff Sunday",            date:"2026-09-06", time:"10:00 AM", location:"Main Sanctuary",     type:"Worship",  lead:"All Staff",       attendees:0,   notes:"New fall season launch — new series announcement" },
];

// ── Transactions — 13 weeks of giving (May – July) ────────────────────────────
export const SEED_TRANSACTIONS = [
  // MAY
  { id:301, date:"2026-05-04", type:"Income",  category:"Tithes & Offerings", amount:16840, description:"Sunday offering — May 4",            account:"General Fund"  },
  { id:302, date:"2026-05-04", type:"Income",  category:"Online Giving",       amount:5210,  description:"Online giving — week of May 4",      account:"General Fund"  },
  { id:303, date:"2026-05-05", type:"Expense", category:"Facilities",          amount:3200,  description:"Utility bills — May",                account:"Operations"    },
  { id:304, date:"2026-05-07", type:"Expense", category:"Staff",               amount:42500, description:"Bi-weekly payroll — May 7",          account:"Payroll"       },
  { id:305, date:"2026-05-09", type:"Expense", category:"Ministry",            amount:1240,  description:"VBS supplies — initial purchase",    account:"Children Fund" },
  { id:306, date:"2026-05-10", type:"Income",  category:"Tithes & Offerings", amount:21320, description:"Mother's Day offering — May 10",     account:"General Fund"  },
  { id:307, date:"2026-05-10", type:"Income",  category:"Online Giving",       amount:7840,  description:"Online giving — week of May 10",     account:"General Fund"  },
  { id:308, date:"2026-05-10", type:"Income",  category:"Special Giving",      amount:3500,  description:"Mother's Day special envelope",      account:"General Fund"  },
  { id:309, date:"2026-05-12", type:"Expense", category:"Marketing",           amount:620,   description:"Mother's Day social campaign",       account:"Marketing"     },
  { id:310, date:"2026-05-17", type:"Income",  category:"Tithes & Offerings", amount:17600, description:"Sunday offering — May 17",           account:"General Fund"  },
  { id:311, date:"2026-05-17", type:"Income",  category:"Online Giving",       amount:5480,  description:"Online giving — week of May 17",     account:"General Fund"  },
  { id:312, date:"2026-05-20", type:"Expense", category:"Staff",               amount:42500, description:"Bi-weekly payroll — May 21",         account:"Payroll"       },
  { id:313, date:"2026-05-21", type:"Expense", category:"Equipment",           amount:1800,  description:"Wireless mic system repair",         account:"Operations"    },
  { id:314, date:"2026-05-24", type:"Income",  category:"Tithes & Offerings", amount:15100, description:"Sunday offering — May 24 (holiday)", account:"General Fund"  },
  { id:315, date:"2026-05-24", type:"Income",  category:"Online Giving",       amount:4900,  description:"Online giving — week of May 24",     account:"General Fund"  },
  { id:316, date:"2026-05-31", type:"Income",  category:"Tithes & Offerings", amount:18200, description:"Sunday offering — May 31",           account:"General Fund"  },
  { id:317, date:"2026-05-31", type:"Income",  category:"Online Giving",       amount:5890,  description:"Online giving — week of May 31",     account:"General Fund"  },
  { id:318, date:"2026-05-31", type:"Expense", category:"Facilities",          amount:1200,  description:"Janitorial services — May",          account:"Operations"    },
  // JUNE
  { id:319, date:"2026-06-04", type:"Expense", category:"Staff",               amount:42500, description:"Bi-weekly payroll — June 4",         account:"Payroll"       },
  { id:320, date:"2026-06-07", type:"Income",  category:"Tithes & Offerings", amount:18640, description:"Sunday offering — June 7",           account:"General Fund"  },
  { id:321, date:"2026-06-07", type:"Income",  category:"Online Giving",       amount:6120,  description:"Online giving — week of June 7",     account:"General Fund"  },
  { id:322, date:"2026-06-08", type:"Income",  category:"Events",              amount:4150,  description:"VBS registration fees — 138 kids",  account:"Children Fund" },
  { id:323, date:"2026-06-10", type:"Expense", category:"Ministry",            amount:2800,  description:"VBS final supplies & decorations",  account:"Children Fund" },
  { id:324, date:"2026-06-14", type:"Income",  category:"Tithes & Offerings", amount:20100, description:"Sunday offering — June 14 (post-VBS)",account:"General Fund" },
  { id:325, date:"2026-06-14", type:"Income",  category:"Online Giving",       amount:7200,  description:"Online giving — week of June 14",    account:"General Fund"  },
  { id:326, date:"2026-06-18", type:"Expense", category:"Staff",               amount:42500, description:"Bi-weekly payroll — June 18",        account:"Payroll"       },
  { id:327, date:"2026-06-20", type:"Expense", category:"Missions",            amount:8400,  description:"Guatemala mission trip expenses",    account:"Missions Fund" },
  { id:328, date:"2026-06-21", type:"Income",  category:"Missions",            amount:6800,  description:"Mission trip love offering",         account:"Missions Fund" },
  { id:329, date:"2026-06-21", type:"Income",  category:"Tithes & Offerings", amount:19400, description:"Sunday offering — June 21",          account:"General Fund"  },
  { id:330, date:"2026-06-21", type:"Income",  category:"Online Giving",       amount:6340,  description:"Online giving — week of June 21",    account:"General Fund"  },
  { id:331, date:"2026-06-24", type:"Expense", category:"Facilities",          amount:3200,  description:"Utility bills — June",               account:"Operations"    },
  { id:332, date:"2026-06-28", type:"Income",  category:"Tithes & Offerings", amount:19800, description:"Sunday offering — June 28",          account:"General Fund"  },
  { id:333, date:"2026-06-28", type:"Income",  category:"Online Giving",       amount:6700,  description:"Online giving — week of June 28",    account:"General Fund"  },
  { id:334, date:"2026-06-28", type:"Income",  category:"Events",              amount:1200,  description:"Summer BBQ concessions & donations", account:"General Fund"  },
  // JULY
  { id:335, date:"2026-07-02", type:"Expense", category:"Staff",               amount:42500, description:"Bi-weekly payroll — July 2",         account:"Payroll"       },
  { id:336, date:"2026-07-05", type:"Income",  category:"Tithes & Offerings", amount:16200, description:"Sunday offering — July 5 (holiday)", account:"General Fund"  },
  { id:337, date:"2026-07-05", type:"Income",  category:"Online Giving",       amount:5100,  description:"Online giving — week of July 5",     account:"General Fund"  },
  { id:338, date:"2026-07-08", type:"Expense", category:"Ministry",            amount:1850,  description:"Youth camp final supplies",          account:"Youth Fund"    },
  { id:339, date:"2026-07-11", type:"Income",  category:"Tithes & Offerings", amount:22400, description:"Revival Night 1 offering — July 11", account:"General Fund"  },
  { id:340, date:"2026-07-12", type:"Income",  category:"Tithes & Offerings", amount:20100, description:"Sunday offering — July 12",          account:"General Fund"  },
  { id:341, date:"2026-07-12", type:"Income",  category:"Online Giving",       amount:7600,  description:"Online giving — week of July 12",    account:"General Fund"  },
  { id:342, date:"2026-07-16", type:"Expense", category:"Staff",               amount:42500, description:"Bi-weekly payroll — July 16",        account:"Payroll"       },
  { id:343, date:"2026-07-17", type:"Expense", category:"Facilities",          amount:3200,  description:"Utility bills — July",               account:"Operations"    },
  { id:344, date:"2026-07-18", type:"Income",  category:"Events",              amount:4200,  description:"Women's Conference registrations",   account:"General Fund"  },
  { id:345, date:"2026-07-18", type:"Income",  category:"Tithes & Offerings", amount:24800, description:"Revival Night 2 + Women's Conf offering",account:"General Fund"},
  { id:346, date:"2026-07-19", type:"Income",  category:"Tithes & Offerings", amount:21600, description:"Sunday offering — July 19",          account:"General Fund"  },
  { id:347, date:"2026-07-19", type:"Income",  category:"Online Giving",       amount:8100,  description:"Online giving — week of July 19",    account:"General Fund"  },
  { id:348, date:"2026-07-20", type:"Expense", category:"Facilities",          amount:1200,  description:"Janitorial services — July",         account:"Operations"    },
  { id:349, date:"2026-07-20", type:"Expense", category:"Marketing",           amount:780,   description:"Social media ads — July",            account:"Marketing"     },
  { id:350, date:"2026-07-25", type:"Income",  category:"Tithes & Offerings", amount:28600, description:"Revival Night 3 offering — July 25 (18 salvations)",account:"General Fund"},
  { id:351, date:"2026-07-26", type:"Income",  category:"Tithes & Offerings", amount:22800, description:"Sunday offering — July 26 (revival follow-up)",account:"General Fund"},
  { id:352, date:"2026-07-26", type:"Income",  category:"Online Giving",       amount:9400,  description:"Online giving — week of July 26",    account:"General Fund"  },
  { id:353, date:"2026-07-26", type:"Income",  category:"Special Giving",      amount:6200,  description:"Revival special mission envelope",   account:"Missions Fund" },
  { id:354, date:"2026-07-28", type:"Expense", category:"Equipment",           amount:2400,  description:"Sound system upgrade — new board",   account:"Operations"    },
];

export const SEED_CAMPAIGNS = [
  { id:401, name:"Mother's Day Service",       type:"Event",    status:"Completed", channel:["Email","Social","SMS"], reach:2840, opens:74, startDate:"2026-04-28", endDate:"2026-05-10", description:"Mother's Day service promotion — record 521 attendance" },
  { id:402, name:"VBS Jungle Journey",         type:"Event",    status:"Completed", channel:["Email","Social","SMS","Website"], reach:3200, opens:82, startDate:"2026-05-12", endDate:"2026-06-12", description:"VBS registration drive — 138 kids enrolled, 6 salvations" },
  { id:403, name:"Guatemala Mission Trip",     type:"Outreach", status:"Completed", channel:["Email","Bulletin"],    reach:1100, opens:68, startDate:"2026-05-20", endDate:"2026-06-28", description:"Mission trip fundraising & prayer support campaign" },
  { id:404, name:"Summer Kickoff BBQ",         type:"Event",    status:"Completed", channel:["Social","Website","SMS"], reach:1860, opens:61, startDate:"2026-06-15", endDate:"2026-06-28", description:"Community BBQ — 287 attended, 41 first-time visitors" },
  { id:405, name:"Summer Revival Series",      type:"Event",    status:"Active",    channel:["Email","Social","SMS","Website"], reach:4100, opens:71, startDate:"2026-07-01", endDate:"2026-08-01", description:"3-night revival with Bishop Raymond Cole — 18 salvations so far" },
  { id:406, name:"Women's Conference",         type:"Event",    status:"Active",    channel:["Email","Social","Print"], reach:2600, opens:78, startDate:"2026-07-01", endDate:"2026-07-19", description:"Walking in Purpose conference — sold out, 201 attended Day 2" },
  { id:407, name:"Back-to-School Drive",       type:"Outreach", status:"Active",    channel:["Social","Website","SMS"], reach:1940, opens:55, startDate:"2026-07-13", endDate:"2026-08-20", description:"School supplies for local kids in need" },
  { id:408, name:"Fall Kickoff Sunday",        type:"Event",    status:"Draft",     channel:["Email","Social"],       reach:0,    opens:0,  startDate:"2026-09-01", endDate:"2026-09-06", description:"New fall season launch campaign" },
  { id:409, name:"Annual Stewardship Campaign",type:"Finance",  status:"Planned",   channel:["Email","Print","Bulletin"],reach:0,  opens:0,  startDate:"2026-10-01", endDate:"2026-10-31", description:"Annual giving & pledge campaign" },
];

export const SEED_ANNOUNCEMENTS = [
  // MAY (archived)
  { id:501, title:"Mother's Day — Bring Your Family",       body:"This Sunday is Mother's Day! Join us for a special service honoring the mothers in our lives. Extended parking will be available and a special gift will be given to every mother in attendance.",            category:"Event",   published:true,  date:"2026-05-05", channels:["Bulletin","Website","Social","Email"] },
  { id:502, title:"VBS Registration Now Open!",             body:"Vacation Bible School is coming! Jungle Journey runs June 8–12 for kids ages 4–12. Register online or at the welcome desk. Volunteer sign-ups also open — we need 40+ helpers!",                          category:"Event",   published:true,  date:"2026-05-13", channels:["Bulletin","Website","Social","Email","SMS"] },
  { id:503, title:"Guatemala Mission Trip — Final Spots",   body:"Two spots remaining on our June 22 Guatemala mission trip. Join 14 church members for 7 days of building, ministry, and outreach. Cost: $1,800. Scholarships available. See Robert Garcia.",              category:"Missions",published:true,  date:"2026-05-18", channels:["Bulletin","Social"] },
  // JUNE
  { id:504, title:"VBS This Week — Jungle Journey!",        body:"VBS starts Monday, June 8! Drop off is 8:45 AM, pickup is 12:15 PM. Family Night is Thursday — bring the whole family at 6:30 PM for our closing celebration on Friday!",                                  category:"Event",   published:true,  date:"2026-06-05", channels:["Bulletin","Website","Social","SMS"] },
  { id:505, title:"Mission Team Send-Off — Pray for Them!", body:"14 members of our church family depart for Guatemala on June 22. Join us for a commissioning service June 21. Pray for safety, open hearts, and spiritual fruit throughout their journey.",                 category:"Missions",published:true,  date:"2026-06-18", channels:["Bulletin","Social","Email"] },
  { id:506, title:"Summer Kickoff BBQ — Invite Everyone",   body:"FREE community BBQ on June 28 at 1 PM on the church grounds. Bring your neighbors, coworkers, and friends! Live music, games, food, and great community. This is our biggest outreach of the summer.",    category:"Outreach",published:true,  date:"2026-06-22", channels:["Bulletin","Website","Social","SMS"] },
  // JULY
  { id:507, title:"Summer Revival — Bishop Raymond Cole",   body:"Don't miss our 3-night Summer Revival featuring Bishop Raymond Cole — July 11, 18, and 25 at 7 PM. Come expecting a move of God! Share this with everyone you know.",                                    category:"Event",   published:true,  date:"2026-07-06", channels:["Bulletin","Website","Social","SMS","Email"] },
  { id:508, title:"Women's Conference: Walking in Purpose", body:"July 18–19 | Main Sanctuary. Two powerful days with speaker Pastor Diane Carter. Registration: $25. Tables of 8 available. Includes worship, breakout sessions, and catered lunch both days.",           category:"Event",   published:true,  date:"2026-07-07", channels:["Bulletin","Social","Email","Print"] },
  { id:509, title:"Back-to-School Supply Drive",            body:"Help us bless local kids with school supplies! Drop boxes are in the lobby through August 20. Most needed: backpacks, composition notebooks, pencils, and colored pencils.",                               category:"Outreach",published:true,  date:"2026-07-13", channels:["Bulletin","Website","Social"] },
  { id:510, title:"Revival Follow-Up: New Believers Class", body:"Did you make a decision at Revival? Or want to grow deeper? Join our New Believers class every Sunday at 9 AM in Room 101. Pastor Russell will personally welcome you.",                                  category:"Ministry",published:true,  date:"2026-07-27", channels:["Bulletin","Website"] },
  { id:511, title:"Staff Appreciation Sunday — Aug 3",      body:"Mark your calendars for August 3rd! We will honor our incredible staff and volunteers who faithfully serve this church year-round. Bring a card, a word of encouragement, or a small gift.",              category:"General", published:false, date:"2026-07-25", channels:["Bulletin","Website","Social"] },
  { id:512, title:"Fall Kickoff Sunday — September 6",      body:"A new season is coming! Fall Kickoff Sunday on September 6 will launch our new sermon series, open Life Group sign-ups, and celebrate everything God is doing at our church. Save the date!",           category:"Event",   published:false, date:"2026-07-25", channels:["Email","Social"] },
];

export const BUDGETS = [
  { dept:"General Operations", allocated:180000, spent:112400 },
  { dept:"Staff & Payroll",    allocated:680000, spent:425000 },
  { dept:"Worship & Arts",     allocated:18000,  spent:10800  },
  { dept:"Children's Ministry",allocated:22000,  spent:15400  },
  { dept:"Youth Ministry",     allocated:16000,  spent:11200  },
  { dept:"Outreach & Missions",allocated:35000,  spent:19600  },
  { dept:"Marketing & Comms",  allocated:24000,  spent:13600  },
  { dept:"Facilities",         allocated:95000,  spent:62300  },
];
